@TicketFly.WebApi_HostAddress = https://localhost:6001
@JwtKey = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo2MTAwIiwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NjEwMCIsImV4cCI6MTc0ODgwNjY0OSwic3ViIjoiMWExMmVmM2UtYjM4NC00MDg0LWYxZmYtMDhkZDllYmI1YjZhIiwiZW1haWwiOiJ1c2VyMUBvZ3V6eWlsZGl6Lm5ldCIsImlhdCI6MTc0ODU5MDY0OSwibmJmIjoxNzQ4NTkwNjQ5fQ.PvJwHjZqP8-1hhFr6nl0NoOUcC-AVZxsbtoW1JSu8rs

#region
GET {{TicketFly.WebApi_HostAddress}}/clients/
Accept: application/json
Authorization: Bearer {{JwtKey}}

###

#region
GET {{TicketFly.WebApi_HostAddress}}/clients/491217de-6204-475a-6891-08dd9ebd50f4
Accept: application/json
Authorization: Bearer {{JwtKey}}

###

#region
POST {{TicketFly.WebApi_HostAddress}}/clients/
Content-Type: application/json
Authorization: Bearer {{JwtKey}}
{
    "name": "Client3",
    "email": "Client3@clientdomain.com",
    "domain": "client3domain.com"
}
###

#region
PUT {{TicketFly.WebApi_HostAddress}}/clients/
Content-Type: application/json
Authorization: Bearer {{JwtKey}}
{
    "id": "492237de-6204-475a-6891-08dd9ebd50f4",
    "name": "",
    "email": "Client1@clientdomain.com",
    "domain": "clientdomain.com"
}
###

#region
POST {{TicketFly.WebApi_HostAddress}}/users/register
Content-Type: application/json
{
    "username": "user1",
    "email": "user1@oguzyildiz.net",
    "firstname": "oguz",
    "lastname": "yildiz",
    "password": "user1@"
}
###

#region
POST {{TicketFly.WebApi_HostAddress}}/users/login
Content-Type: application/json
{
    "email": "user1@oguzyildiz.net",
    "password": "user1@"
}
###
