@TicketFly.WebApi_HostAddress = https://localhost:6001

#region
GET {{TicketFly.WebApi_HostAddress}}/clients/
Accept: application/json

###

#region
GET {{TicketFly.WebApi_HostAddress}}/clients/{id}
Accept: application/json

###

#region
POST {{TicketFly.WebApi_HostAddress}}/clients/
Content-Type: application/json
{
    "name": "Client2",
    "email": "Client2@clientdomain.com",
    "domain": "client2domain.com"
}
###

#region
PUT {{TicketFly.WebApi_HostAddress}}/clients/
Content-Type: application/json
{
    "id": "492237de-6204-475a-6891-08dd9ebd50f4",
    "name": "Client1-Updated-3",
    "email": "Client1@clientdomain.com",
    "domain": "clientdomain.com"
}
###

#region
POST {{TicketFly.WebApi_HostAddress}}/users/register
Content-Type: application/json
{
    "username": "user1",
    "email": "user1@oguzyildiz.net",
    "firstname": "oguz",
    "lastname": "yildiz",
    "password": "user1@"
}
###

#region
POST {{TicketFly.WebApi_HostAddress}}/users/login
Content-Type: application/json
{
    "email": "user1@oguzyildiz.net",
    "password": "user1@2"
}
###
